---
#######  Archive installation #######

- name: Create installation directory
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory
  when: install_type == "archive"

- name: Download Ansible archive ({{ archive_url }})
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ checksum_format }}:{{ archive_checksum }}"
    mode: '0775'
  register: archive_tmp
  become: true
  when: install_type == "archive"

- name: Extract Ansible archive
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    mode: '0775'
    extra_opts:
      - --strip-components
      - '1'
    remote_src: true
  become: true
  when: install_type == "archive"

- name: check if local bin file exists
  stat:
    path: /usr/local/bin/ansible
  register: local_bin

- name: Create a symbolic link to /usr/local/bin/ansible
  become: true
  file:
    src: "{{ install_dir }}/bin/ansible"
    dest: /usr/local/bin/ansible
    state: link
  when: install_type == "archive" and not local_bin.stat.exists
