---
- name: Create config dir
  become: true
  file:
    path: "{{ config_dir }}"
    owner: "{{ controller_user }}"
    group: "{{ controller_user }}"
    state: directory

- name: Create log file path
  become: true
  file:
    path: "{{ config.defaults.log_path }}"
    owner: "{{ controller_user }}"
    group: "{{ controller_user }}"
    state: touch
  when: config.defaults.log_path is defined and config.defaults.log_path|length > 0

- name: Render Ansible configuration
  become: true
  template:
    src: "{{ ansible_config_file }}.j2"
    dest: "{{ config_dir }}/{{ ansible_config_file }}"
    owner: "{{ controller_user }}"
    group: "{{ controller_user }}"
    mode: 0644
  vars:
    conf: "{{ config }}"
  when: config is defined and config.keys()|length > 0

- name: Set system-wide configuration dir envvar
  become: true
  copy:
    dest: /etc/profile.d/ansible-vars.sh
    content: 'ANSIBLE_CONFIG={{ config_dir }}'
