---
- name: Ensure existence of config dir
  become: true
  file:
    path: "{{ config.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Copy Ansible configuration in place
  become: true
  template:
    src: "{{ ansible_config_file }}.j2"
    dest: "{{ item.path }}/{{ item.name|ansible_config_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  vars:
    conf: "{{ item.config }}"
  when: item.config is defined and item.config is not none
