---
- name: Create Ansible controller group
  become: true
  group:
    name: "{{ controller_user }}"
    state: present
    system: true

- name: Create Ansible controller user
  become: true
  user:
    comment: Ansible controller service account
    name: "{{ controller_user }}"
    group: "{{ controller_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false

- name: Install controller based on install type
  include_tasks: "common/install/{{ install_type }}_install.yml"

- name: Install galaxy content
  include_tasks: "common/install/galaxy_install.yml"
