---
- name: Ensure Ansible controller group exists
  group:
    name: "{{ controller_user }}"
    state: present
  become: true

- name: Create Ansible controller user
  user:
    comment: Ansible controller service account
    name: "{{ controller_user }}"
    group: "{{ controller_user }}"
  become: true

- name: perform designated installation procedure
  include_tasks: "common/{{ install_type }}_install.yml"
