---
- name: Install Ansible galaxy roles
  become: true
  become_user: "{{ controller_user }}"
  command: "ansible-galaxy role install {{ item }} {{ galaxy_extra_args | join(' ') }}"
  loop: "{{ galaxy_roles }}"
  when: galaxy_roles is defined and galaxy_roles|length > 0

- name: Install Ansible galaxy collections
  become: true
  become_user: "{{ controller_user }}"
  command: "ansible-galaxy collection install {{ item }} {{ galaxy_extra_args | join(' ') }}"
  loop: "{{ galaxy_collections }}"
  when: galaxy_collections is defined and galaxy_collections|length > 0
